// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauranteWeb.Infra.Data.Context;

namespace RestauranteWeb.Infra.Data.Migrations
{
    [DbContext(typeof(RestauranteWebContext))]
    partial class RestauranteWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestauranteWeb.Domain.Entities.Pratos.Prato", b =>
                {
                    b.Property<Guid>("IdEntidade")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataHoraCadastro");

                    b.Property<DateTime>("DataHoraInativacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("Preco");

                    b.Property<Guid>("RestauranteId");

                    b.Property<byte>("StatusRegistro");

                    b.Property<Guid>("UsuarioCriador");

                    b.Property<Guid>("UsuarioInativacao");

                    b.HasKey("IdEntidade")
                        .HasName("PratoId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Pratos");
                });

            modelBuilder.Entity("RestauranteWeb.Domain.Entities.Restaurantes.Restaurante", b =>
                {
                    b.Property<Guid>("IdEntidade")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataHoraCadastro");

                    b.Property<DateTime>("DataHoraInativacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte>("StatusRegistro");

                    b.Property<Guid>("UsuarioCriador");

                    b.Property<Guid>("UsuarioInativacao");

                    b.HasKey("IdEntidade")
                        .HasName("RestauranteId");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("RestauranteWeb.Domain.Entities.Pratos.Prato", b =>
                {
                    b.HasOne("RestauranteWeb.Domain.Entities.Restaurantes.Restaurante", "Restaurante")
                        .WithMany("Pratos")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
